"""add closed_by_id to ticket

Revision ID: 1ef45fed2df9
Revises: c931a00ed2e2
Create Date: 2026-08-27 16:37:57.457766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ef45fed2df9'
down_revision: Union[str, Sequence[str], None] = 'c931a00ed2e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('closed_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'user', ['closed_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'closed_by_id')
    # ### end Alembic commands ###
