"""add_indexes_and_constraints

Revision ID: a5e5c260e8f4
Revises: 1ef45fed2df9
Create Date: 2026-08-28 08:25:54.347495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5e5c260e8f4'
down_revision: Union[str, Sequence[str], None] = '1ef45fed2df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_comments_ticketr_id'), 'comments', ['ticketr_id'], unique=False)
    op.create_index('ix_tickets_assigned_status', 'tickets', ['assigned_to_id', 'status'], unique=False)
    op.create_index('ix_tickets_assigned_to', 'tickets', ['assigned_to_id'], unique=False)
    op.create_index('ix_tickets_category', 'tickets', ['category_id'], unique=False)
    op.create_index('ix_tickets_created_by', 'tickets', ['created_by_id'], unique=False)
    op.create_index('ix_tickets_creator_status', 'tickets', ['created_by_id', 'status'], unique=False)
    op.create_index('ix_tickets_priority', 'tickets', ['priority'], unique=False)
    op.create_index('ix_tickets_status', 'tickets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tickets_status', table_name='tickets')
    op.drop_index('ix_tickets_priority', table_name='tickets')
    op.drop_index('ix_tickets_creator_status', table_name='tickets')
    op.drop_index('ix_tickets_created_by', table_name='tickets')
    op.drop_index('ix_tickets_category', table_name='tickets')
    op.drop_index('ix_tickets_assigned_to', table_name='tickets')
    op.drop_index('ix_tickets_assigned_status', table_name='tickets')
    op.drop_index(op.f('ix_comments_ticketr_id'), table_name='comments')
    # ### end Alembic commands ###
